export const videos = [
    {
        title: "Tuto Comment faire 140K",
        channel: "TrqR",
        views: "140 000 euros",
        date: "il y a 3 semaines",
        thumbnail: "images/vidtristan.jpg",
    },
    {
        title: "Comment bien faire des pompes",
        channel: "YusufInShape",
        views: "9 400 000 vues",
        date: "il y a 2 mois",
        thumbnail: "images/vidyusuf.jpg",
    },
    {
        title: "Ciao Kombucha",
        channel: "Squeezie",
        views: "1 800 000 vues",
        date: "il y a 1 mois",
        thumbnail: "images/vid2.jpg",
    },
    {
        title: "Javascript pour les phacochères",
        channel: "Pilou",
        views: "220 000 vues",
        date: "il y a 2 jours",
        thumbnail: "images/vidpilou.jpg",
    },
    {
        title: "Les Maths Facile",
        channel: "Yousra",
        views: "0001 vues",
        date: "il y a 10 jours",
        thumbnail: "images/vid4.jpg",
    },
    {
        title: "JavaScript c'est cool en français",
        channel: "Alexis",
        views: "220 000 vues",
        date: "il y a 2 jours",
        thumbnail: "images/vid5.jpg",
    },
    {
        title: "Apple ou Samsung?",
        channel: "SteveJobs",
        views: "2 200 000 vues",
        date: "il y a 20 ans",
        thumbnail: "images/vid6.jpg",
    },
    {
        title: "La journée totalement crazy | VLOG Londres",
        channel: "MariamNotMyriam",
        views: "450 000 vues",
        date: "il y a 3 heures",
        thumbnail: "images/vid1.jpg",
    },
    {
        title: "DayZ | l'histoire sans fin EP.974",
        channel: "Zentax",
        views: "100 vues",
        date: "il y a 3 semaines",
        thumbnail: "images/vidjason.jpg",
    },
];